KB = 0x400
MB = KB**2
GB = KB**3
MAX_BUFFER_SIZE = 0xFFFF
BUFFER = KB
FORMAT = "utf-8"
FLAG_R = {0: "0 - Reserved bit"}
FLAG_DF = {0: "0 - Fragment if necessary", 1: "1 - Do not Fragment"}
FLAG_MF = {0: "0 - Last Fragment", 1: "1 - More Fragments"}
IPV4_HL = 20
IPV6_HL = 40
TCP_HL = 20
UDP_HL = 8
